name: ESLint

on:
  push:
    branches:
      - master
      - feature-ci-lint
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn
      - run: yarn build
      - run: eslint .
