name: ESLint

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn
      - run: yarn lint
